# -*- coding: utf-8 -*-
"""Text analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NZmeO2u0dy7TOzFdlF_UG6-sUwh5jpOi
"""

givenstring="Lorem ipsum dolor! diam amet, consetetur Lorem magna. sed diam nonumy eirmod tempor. diam et labore? et diam magna. et diam amet."

class TextAnalyzer(object):
  def __init__(self, text):
    formatted_text = text.replace("."," ").replace('!','').replace('?','').replace(',','')
    formatted_text.lower()
    self.fmtText = formatted_text

  def freqAll(self):
    wordList = self.fmtText.split(" ")
    freqMap = {}
    for word in wordList:
      freqMap[word] = wordList.count(word)
    return freqMap
  def freqOf(self,word):
    freqDict = self.freqAll()
    if word in freqDict:
      return freqDict[word]
    else:
      return 0

